# Generated by Django 3.2.7 on 2022-02-07 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='recipes',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='shoppingcard',
            old_name='recipes',
            new_name='recipe',
        ),
    ]
