# Generated by Django 3.2.7 on 2022-02-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220207_1630'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipeingredient',
            name='unique_recipeingridient',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcard',
            name='unique_shoppingcard',
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('ingredient', 'recipe'), name='unique_recipeingridient'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcard',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_shoppingcard'),
        ),
    ]
