version: '3.3'
services:

  db:
    image: postgres:12.4-alpine
    container_name: db
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    env_file:
        - ./.env
  frontend:
    image: slavastan/frontend:v1
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ./docs:/usr/share/nginx/html/api/docs/
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
    depends_on:
      - backend

  backend:
    image: slavastan/foodgram:latest
    container_name: backend
    restart: always
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
volumes:
  postgres_data:
  static_volume:
  media_volume: